-- =========================================
-- Migración V3: Nuevo Esquema UXDUAL (PostgreSQL 14+)
-- - CBU/CVU como texto con validación 22 dígitos
-- - Únicos en CUIT, email, DNI, CBU, CVU, alias de cuenta
-- - IDENTITY en lugar de SERIAL
-- =========================================

-- Backup de datos existentes antes de la migración
CREATE TEMPORARY TABLE backup_payments AS SELECT * FROM payments;
CREATE TEMPORARY TABLE backup_users AS SELECT * FROM users;

-- Eliminar esquema anterior
DROP TABLE IF EXISTS ux_usuario_rol CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS ux_rol CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS venta CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS caja CASCADE;
DROP TABLE IF EXISTS sucursal CASCADE;
DROP TABLE IF EXISTS empresa CASCADE;

-- Eliminar tipos personalizados del esquema anterior
DROP TYPE IF EXISTS estado_pago CASCADE;
DROP TYPE IF EXISTS metodo_pago CASCADE;
DROP TYPE IF EXISTS estado_venta CASCADE;

-- Crear esquema UXDUAL
DROP SCHEMA IF EXISTS uxdual CASCADE;
CREATE SCHEMA uxdual;

-- ========================
-- Tablas base
-- ========================

CREATE TABLE uxdual.Estado (
  estadoId      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(100) NOT NULL,
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.Direccion (
  direccionId   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calle         VARCHAR(150),
  fechaCreacion DATE DEFAULT CURRENT_DATE,
  numero        INT,
  piso          VARCHAR(20),
  barrio        VARCHAR(100)
);

CREATE TABLE uxdual.Comercio (
  comercioId    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(150) NOT NULL,
  cuit          VARCHAR(20)  NOT NULL UNIQUE,
  estadoId      INT REFERENCES uxdual.Estado(estadoId),
  fechaCreacion DATE DEFAULT CURRENT_DATE
);

CREATE TABLE uxdual.Sucursal (
  sucursalId    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comercioId    INT NOT NULL REFERENCES uxdual.Comercio(comercioId),
  direccionId   INT REFERENCES uxdual.Direccion(direccionId),
  nombre        VARCHAR(150) NOT NULL,
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.CuentaBancaria (
  cuentaId      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursalId    INT NOT NULL REFERENCES uxdual.Sucursal(sucursalId),
  alias         VARCHAR(50) UNIQUE,
  -- CBU/CVU como TEXTO para conservar ceros iniciales y no exceder BIGINT
  cbu           VARCHAR(22),
  cvu           VARCHAR(22),
  banco         VARCHAR(100),
  estadoId      INT REFERENCES uxdual.Estado(estadoId),
  -- Validación opcional de formato de 22 dígitos
  CONSTRAINT cbu_formato_chk CHECK (cbu IS NULL OR cbu ~ '^[0-9]{22}$'),
  CONSTRAINT cvu_formato_chk CHECK (cvu IS NULL OR cvu ~ '^[0-9]{22}$'),
  CONSTRAINT cbu_unico UNIQUE (cbu),
  CONSTRAINT cvu_unico UNIQUE (cvu)
);

CREATE TABLE uxdual.PuntoVta (
  puntoVtaId    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursalId    INT NOT NULL REFERENCES uxdual.Sucursal(sucursalId),
  estadoId      INT REFERENCES uxdual.Estado(estadoId),
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.Usuario (
  empleadoId    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursalId    INT REFERENCES uxdual.Sucursal(sucursalId),
  nombre        VARCHAR(100) NOT NULL,
  apellido      VARCHAR(100),
  email         VARCHAR(150) UNIQUE,
  telefono      VARCHAR(50),
  estadoId      INT REFERENCES uxdual.Estado(estadoId),
  fechaCreacion DATE DEFAULT CURRENT_DATE,
  dni           VARCHAR(20) UNIQUE,
  pinHash       VARCHAR(255)
);

CREATE TABLE uxdual.Rol (
  rolId         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(100) NOT NULL,
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.UserRol (
  empRolId      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empleadoId    INT NOT NULL REFERENCES uxdual.Usuario(empleadoId),
  rolId         INT NOT NULL REFERENCES uxdual.Rol(rolId),
  CONSTRAINT userrol_unico UNIQUE (empleadoId, rolId)
);

CREATE TABLE uxdual.Permiso (
  permisoId     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(100) NOT NULL,
  alias         VARCHAR(50),
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.Recurso (
  recursoId     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(100) NOT NULL,
  alias         VARCHAR(50),
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.RolResPer (
  rolResPerId   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rolId         INT REFERENCES uxdual.Rol(rolId),
  permisoId     INT REFERENCES uxdual.Permiso(permisoId),
  recursoId     INT REFERENCES uxdual.Recurso(recursoId),
  CONSTRAINT rol_perm_recurso_unico UNIQUE (rolId, permisoId, recursoId)
);

CREATE TABLE uxdual.Qr (
  qrId          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estadoId      INT REFERENCES uxdual.Estado(estadoId),
  puntoVtaId    INT REFERENCES uxdual.PuntoVta(puntoVtaId),
  fechaCreacion DATE DEFAULT CURRENT_DATE,
  ultimaRotacion DATE,
  tokenHash     VARCHAR(255)
);

CREATE TABLE uxdual.EstadoTransaccion (
  estadoTrxId   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(100) NOT NULL,
  descripcion   VARCHAR(255)
);

CREATE TABLE uxdual.Trx (
  trxId         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qrId          INT REFERENCES uxdual.Qr(qrId),
  estadoTrxId   INT REFERENCES uxdual.EstadoTransaccion(estadoTrxId),
  monto         NUMERIC(15,2),
  metodo        VARCHAR(50),
  moneda        VARCHAR(10),
  fechaCreacion DATE DEFAULT CURRENT_DATE,
  fechaAprobacion DATE,
  idempotencyKey  VARCHAR(100),
  originCUIT    VARCHAR(20),
  destinationCUIT VARCHAR(20),
  -- Campos adicionales para compatibilidad con sistema actual
  paymentId     VARCHAR(100) UNIQUE,
  orderId       VARCHAR(100),
  customerName  VARCHAR(255),
  branchName    VARCHAR(255),
  cashierName   VARCHAR(255),
  createdAt     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastSyncCursor TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================
-- Índices recomendados (FKs y búsquedas comunes)
-- ========================

CREATE INDEX idx_sucursal_comercio   ON uxdual.Sucursal(comercioId);
CREATE INDEX idx_sucursal_direccion  ON uxdual.Sucursal(direccionId);

CREATE INDEX idx_cuentab_sucursal    ON uxdual.CuentaBancaria(sucursalId);
CREATE INDEX idx_puntovta_sucursal   ON uxdual.PuntoVta(sucursalId);

CREATE INDEX idx_usuario_sucursal    ON uxdual.Usuario(sucursalId);
CREATE INDEX idx_usuario_estado      ON uxdual.Usuario(estadoId);

CREATE INDEX idx_qr_puntovta         ON uxdual.Qr(puntoVtaId);
CREATE INDEX idx_qr_estado           ON uxdual.Qr(estadoId);

CREATE INDEX idx_trx_qr              ON uxdual.Trx(qrId);
CREATE INDEX idx_trx_estado          ON uxdual.Trx(estadoTrxId);
CREATE INDEX idx_trx_fecha           ON uxdual.Trx(fechaCreacion);
CREATE INDEX idx_trx_payment_id      ON uxdual.Trx(paymentId);
CREATE INDEX idx_trx_created_at      ON uxdual.Trx(createdAt);

-- ========================
-- Función para actualizar timestamps
-- ========================

CREATE OR REPLACE FUNCTION uxdual.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updatedAt = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para actualizar timestamps en transacciones
CREATE TRIGGER update_trx_updated_at 
    BEFORE UPDATE ON uxdual.Trx
    FOR EACH ROW EXECUTE FUNCTION uxdual.update_updated_at_column();

-- ========================
-- Crear vistas de compatibilidad para el sistema actual
-- ========================

-- Vista que mapea el nuevo esquema al formato esperado por el backend actual
CREATE VIEW payments AS
SELECT 
    t.trxId as id,
    t.paymentId as payment_id,
    t.orderId as order_id,
    t.customerName as customer_name,
    t.branchName as branch_name,
    t.cashierName as cashier_name,
    t.monto as amount,
    t.metodo as method,
    CASE 
        WHEN et.nombre = 'APROBADA' THEN 'APROBADA'::text
        WHEN et.nombre = 'RECHAZADA' THEN 'RECHAZADA'::text
        WHEN et.nombre = 'PENDIENTE' THEN 'PEND_LIQ'::text
        WHEN et.nombre = 'LIQUIDADA' THEN 'LIQUIDADA'::text
        ELSE 'PEND_LIQ'::text
    END as status,
    t.createdAt as created_at,
    t.updatedAt as updated_at,
    t.lastSyncCursor as last_sync_cursor
FROM uxdual.Trx t
LEFT JOIN uxdual.EstadoTransaccion et ON t.estadoTrxId = et.estadoTrxId;

-- Vista para usuarios
CREATE VIEW users AS
SELECT 
    u.empleadoId as id,
    u.nombre as username,
    u.pinHash as password,
    u.email as email,
    CASE WHEN u.estadoId = 1 THEN true ELSE false END as activo,
    s.comercioId as empresa_id,
    u.fechaCreacion::timestamp as created_at,
    CURRENT_TIMESTAMP as updated_at
FROM uxdual.Usuario u
LEFT JOIN uxdual.Sucursal s ON u.sucursalId = s.sucursalId;